Homepage nav bar
CodeTheDream/rebuilding-together pull request #11
Opened 2019-03-26 19:21 UTC by Kwasi008

Here my first attempt at a nav bar, just wanting some feed back on what I should change and adjust.

@jrmcgarvey @leila-alderman

2019-03-26 19:43 UTC, leila-alderman requested changes
A few small comments. Overall, it looks good!

2019-03-26 19:43 UTC, leila-alderman commented on app/views/layouts/application.html.erb
> +   <%= render 'welcome/nav_bar.html.erb' %>
You don't need the full file extension here.

```suggestion
   <%= render 'welcome/nav_bar' %>
```

2019-03-26 19:43 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +        <li><%= link_to "Log in", '#' %></li>
You should make these links specific to your app and add in routes (if you have them to add).

2019-03-26 19:43 UTC, leila-alderman commented on config/routes.rb
> +  root 'welcome#homepage'
Your `root` path should always be at the top of your `routes.rb` file since Rails looks for routes in order, from top to bottom.

2019-03-27 20:08 UTC, leila-alderman requested changes
Most of my comments are just about writing cleaner code and better leveraging Rails to use less hard-coded HTML. 

In general, please be very careful about copying and pasting code that you don't completely understand. That can quickly get out of hand, and it doesn't help you actually learn. 

As always, please let me know if you have any questions or would like to discuss further!

2019-03-27 20:08 UTC, leila-alderman commented on app/controllers/volunteers_controller.rb
>            redirect_to volunteer_path(@volunteer.id)
Now that you've added the line above, this line should be deleted.

2019-03-27 20:08 UTC, leila-alderman commented on app/controllers/volunteers_controller.rb
>        volunteer = Volunteer.find(params[:id])
If you're using `current_user` to find the volunteer record in the `edit` method, you should probably do the same here.

2019-03-27 20:08 UTC, leila-alderman commented on app/controllers/volunteers_controller.rb
>        redirect_to volunteer_path(volunteer.id)
Again, now that you've added the line above, this line should be deleted.

2019-03-27 20:08 UTC, leila-alderman commented on app/models/user.rb
>    has_one :owner
These two association lines typically go above any methods. I think a good place for these would be above the `devise` line.

2019-03-27 20:08 UTC, leila-alderman commented on app/views/volunteers/_form.html.erb
>                  <%= f.label :birthdate, "Birthdate:" %>
Looks like there are two of these lines. You should probably delete lines 30 and 31.

2019-03-27 20:08 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +  <a class="navbar-brand" <%= link_to "Rebuilding Together", root_path %></a>
You can make this cleaner by using Rails more:

```suggestion
  <%= link_to "Rebuilding Together", root_path, class: "navbar-brand" %>
```

In general, Rails `link_to` is used *instead of* HTML <a> links. This should be cleaned up throughout your code.

2019-03-27 20:08 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +        <a class= "nav-link",<%= link_to "Voluntueer", volunteers_path %> <span class="sr-only">(current)</span></a>
The `sr-only` class is intended to create hidden text fields to be read by screen readers. In particular, this text is intended to work with the `active` class above to indicate the currently active page, which I don't think you plan to use.

2019-03-27 20:08 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +      <li class="nav-item active">
The `active` class is intended to be highlighted to indicate the current page, but if this nav bar is going to be used on all of the pages, then there's no way to toggle the `active` class. Therefore, unless you plan to actually toggle this, it should probably be removed.

2019-03-27 20:08 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +  </button>
It doesn't look like you're using the button at all, so lines 3-5 can be deleted.

2019-03-27 20:08 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +      </li>
All of these list items can be written much more succinctly. For example, you can replace lines 12-14 with one line:

 ```suggestion
      <li><%= link_to "Home Owner", root_path, class: "nav-link" %></li>
```

2019-03-27 20:08 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +      </div>
This closing `div` tag doesn't seem to have a mate. It makes much more sense for this to be a closing `ul` tag.

2019-03-27 20:08 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +    <div>
This opening `div` tag doesn't seem to have a mate. Please delete this.

2019-03-27 20:08 UTC, leila-alderman commented on app/views/welcome/_nav_bar.html.erb
> +       </li>
Please just use `link_to` for these two links (following the format suggested above).

2019-03-28 17:36 UTC, Kwasi008 commented on app/controllers/volunteers_controller.rb
>            redirect_to volunteer_path(@volunteer.id)
Hi Leila in my local resp it doesnt displace like this, It shows that line 34 isnt there at all.

2019-03-29 15:07 UTC, jrmcgarvey commented
Closing pull request.  Kwasi has made additional changes which are in the branch homepage_first, which subsume these changes.

2019-03-29 15:07 UTC, closed without merging